### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by JoeD84** [grochocki/XamlMagic#11]
Hi,

after installing the Plugin I get the following Error:
The 'StylerPackage' package did not load correctly.
...
You can get information by examining the file
...

Contents of the file:
...
`
  <entry>
    <record>108</record>
    <time>2016/03/03 06:14:24.732</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [StylerPackage]</description>
    <guid>{74FDBBF7-6350-4D00-B942-DB64A3B95754}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Das System kann die angegebene Datei nicht finden.</errorinfo>
  </entry>
`
I use VisualStudio 2013.

Best regards
JoeD

**Comment by grochocki** [comment]
XAML Magic currently only official supports [VS2015](https://github.com/grochocki/XamlMagic/wiki) and later, but I will try to get a copy of VS2013 up and running and see what I can do about getting it working there.

**Comment by JoeD84** [comment]
Thank you for the quick reply. Didn't see that, only that it is not working for VS2012.
I'm looking forward for a working copy. XAMLStyler did had some performance issues.

**Comment by KenjiroPL** [comment]
Then please remove compatibility mark from plugin because it is marked as compatible with VS2013 (and upgrades to non working state):
https://visualstudiogallery.msdn.microsoft.com/0d682c2e-3c5e-4f0e-8b54-d37ecb25eb7e

**Comment by grochocki** [comment]
I am in the process of backporting features and bug fixes as well as transitioning issues to (Xavalon/XamlStyler)[https://github.com/Xavalon/XamlStyler/issues]. If this continue to be an issue, please open in a new issue [here](https://github.com/Xavalon/XamlStyler/issues).
