### ISSUE TITLE
Visual Studio 15 support

### ISSUE THREAD

**Issue by xperiandri** [grochocki/XamlMagic#15]

**Comment by grochocki** [comment]
I am not able to repro any issues in Visual Studio 2015.

Regardless, I am in the process of backporting features and bug fixes as well as transitioning issues to (Xavalon/XamlStyler)[https://github.com/Xavalon/XamlStyler/issues]. If this continue to be an issue, please open in a new issue [here](https://github.com/Xavalon/XamlStyler/issues).

**Comment by xperiandri** [comment]
Not 2015 (v14) but v15 Preview
