### ISSUE TITLE
XAML Magic deletes {BOM}

### ISSUE THREAD

**Issue by bschoepke** [grochocki/XamlMagic#18]
1. Create a UserControl with VS2015 Update 2.
2. Run XAML Magic on it with default config.

[Observed]
3. {BOM} is removed from beginning of file (byte order mark)

[Expected]
3. {BOM} is not removed.

Still seems to build and run fine but it would be safer not to mess with {BOM}.

**Comment by grochocki** [comment]
Migrated issue to: https://github.com/Xavalon/XamlStyler/issues/55
