### ISSUE TITLE
The ':' character, hexadecimal value 0x3A, cannot be included in a name.

### ISSUE THREAD

**Issue by keith-hsv** [grochocki/XamlMagic#3]
I am getting this error on one of my XAML files. I don't know what it means.

Can you help me understand it?

I don't have any ':' characters in any of my names as far as I can tell.

**Comment by grochocki** [comment]
Any chance you can figure out which element is causing the error? If you could copy the problem segment here, I can get to the bottom of it.

**Comment by keith-hsv** [comment]
Elements like this cause the error:
<Setter Property="uxt:ButtonControlProperties.CheckedBrush" Value="{uxt:SapphireResource ResourceKey=ListMouseOverBrush}"/>

**Comment by ju2pom** [comment]
I can confirm that we have the same issue.

**Comment by keith-hsv** [comment]
The problem I believe comes from parsing XML. Without registering the namespace used in the attribute, the error will occur.

I was going to try seeing if I could help solve the problem, and contribute a fix, but I've never done OSS before. :P

**Comment by keith-hsv** [comment]
Okay, I found the source of the bug and fixed it. I made a fork, and am submitting a pull request. This is my first OSS contribution. Please be gentle. :D

**Comment by grochocki** [comment]
Thanks, happy XAML Magic motivated you to make your first OSS contribution! I will take a look at the pull request. Will try not to be too picky :)
