### ISSUE TITLE
More styling options

### ISSUE THREAD

**Issue by ju2pom** [grochocki/XamlMagic#4]
Hello,

This extension looks very promising and is almost production ready for us. But we have a formatting practice that we cannot get with the current set of options.
The general rule is that all attributes should be on a separate line including the closing "/>" to ease merge and diffs. But only when an element has a x:Name attribute we keep it on the first line so that when the element is collapsed the name is sill visible.
Here is a short example:
```xml
<control:Viewer x:Name="ViewerControl"
                Background="{StaticResource DarkColorBrush}"
                Layers="{Binding Layers, Mode=OneWay}"
                />
```
We can get such a formatting with the current set of options, but then we always have one attribute on the first line, even if it's not x:Name.

**Comment by grochocki** [comment]
More generically, would this be "Keep First Attribute On Same Line" if Any(<list of elements>) is present? In your case, I believe you would set this to "x:Name, Name", with Attribute Ordering Rule Groups taking care of the rest.

**Comment by ju2pom** [comment]
Yes this is a generic rule that would fit our needs !

**Comment by grochocki** [comment]
First Line Attributes [documentation](https://github.com/grochocki/XamlMagic/wiki/Attribute-Reordering#first-line-attributes-pre-release) updated.
