### ISSUE TITLE
Element Ordering Rule Groups

### ISSUE THREAD

**Issue by punker76** [grochocki/XamlMagic#6]
Hi,

so the XAMLStyler repo seems to be not active anymore, but XAMLMagic seems to be...

It would be nice to have `Element Ordering Rule Groups` like `Attribute Ordering Rule Groups` e.g. to group style `Setters` in the same way.

Jan

**Comment by grochocki** [comment]
Can you elaborate a bit more? There are already a few settings around [element reordering](https://github.com/grochocki/XamlMagic/wiki/Element-Reordering), including [setters](https://github.com/grochocki/XamlMagic/wiki/Element-Reordering#reorder-setters).

**Comment by punker76** [comment]
@grochocki Yes, of course. I know, there is already a setting to reorder Setters, but not to (pre)group this like the attribute ordering does. e.g. I would prefer putting Template setters (Template, HeaderTemplate, ContentTemplate...) to the end of a style...

**Comment by grochocki** [comment]
Good news is XamlStyler has been revived under a new team (including me). I am in the process of backporting features and bug fixes as well as transitioning issues to (Xavalon/XamlStyler)[https://github.com/Xavalon/XamlStyler/issues]. I already transferred this issue as a feature request.
